[package]
name = "trans-screen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
femtovg = { version = "0.9.0", default-features = false }
glutin = "0.31"
glutin-winit = "0.4.2"
raw-window-handle = "0.5"
winit = { version = "0.29", features = ["rwh_05"] }
