[package]
name = "trans-screen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
femtovg = { version = "0.9.0", default-features = false }
glutin = "0.31"
glutin-winit = { version = "0.4.2", default-features = false, features = ["egl", "glx", "x11", "wgl"] }
raw-window-handle = "0.5"
winit = { version = "0.29", default-features = false, features = ["rwh_05"] }
xcap = { git = "https://github.com/alliby/xcap" }

[target.'cfg(target_os = "linux")'.dependencies]
smithay-client-toolkit = "0.18.1"
wayland-backend = { version = "0.3.3", features = ["client_system"] }
wayland-client = "0.31"
