[package]
name = "trans-screen"
version = "0.1.0"
edition = "2021"

[dependencies]
femtovg = { version = "0.9", default-features = false }
glutin = { version = "0.32" }
glutin-winit = { version = "0.5.0" }
winit = { version = "0.30.0", features = ["rwh_06"]}

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = "0.13"
