[package]
name = "trans-screen"
version = "0.1.0"
edition = "2021"

[dependencies]
femtovg = { version = "0.9", default-features = false }
glutin = { version = "0.32", default-features = false, features = ["x11", "libloading", "egl", "glx", "windows-sys"] }
glutin-winit = { version = "0.5.0", default-features = false, features = ["egl", "glx", "x11"] }
winit = { version = "0.30.0", default-features = false, features = ["x11", "rwh_06"] }
x11rb = "0.13"
